- copilot-chat-copilot.el
> chore: update copilot-chat-copilot.el

- copilot-chat-copilot.el
This fixes #16 by making `curl-analyze-copilot-response` more tolerant to the underlying data being truncated in weird spots. This should result in fewer/no `error in process filter: Args out of range: "data:", 6, nil` errors and dropped updates.
---
As you may recall, the protocol seems to send a series of lines like:
```
data: {"choices":[{...,"delta":{"content":"great"}}],...}
data: {"choices":[{...,"delta":{"content":"work"}}],...}
data: [DONE]
```
With the curl-based streaming, these are cut up into chunks at arbitrary boundaries, and passed to `curl-analyze-copilot-response`. The boundaries are truly arbitrary. For instance, in #16, there's an example where one `string` value ends with `dat` and then next one starts `a: {...}`. That is, the `data: ...` prefix is truncated, not just …
> Tolerate truncation of `data: ` prefix in curl streaming

- copilot-chat-curl.el
While answers from the copilot are prefixed with `data: `, error messages are simple JSON payloads.
This change updates the payload handling to correctly react to these side-channel payloads and handles the `error` response type.
Now, when receiving an error (such as Token Limit Exceeded), the error will be displayed to the user, instead of having copilot fail silently.
> fix: Handle side-channel error messages

- Readme.md
- copilot-chat-curl.el
> Manage simple proxies

- copilot-chat-common.el
Also updated to the recent one.
> Feat: Make model configurable

- Readme.md
- copilot-chat-shell-maker.el
- copilot-chat.el
No specific init is needed anymore.
> Fix buffer preparation with shell-maker

- copilot-chat-shell-maker.el
- copilot-chat.el
> shell-maker: preserve input ring across sessions

- copilot-chat-curl.el
I saw that there was no `DATA` format or anything like that,
and I implemented it assuming that o1 would never split JSON unlike the others.
That was not the case, so I fixed it.
I guess it might be due to the fact that I'm getting standard output with curl in the middle.
Since there is no identifier such as `DATA` in the o1 format,
after some thought I decided to use whether the process is alive or not as information.
> fix: work on split JSON respose in on o1

- copilot-chat.el
> feat: align model selection and display formatting

- copilot-chat.el
> Add missing closing paren

- copilot-chat.el
- readme.org
> feat(chat): improve reset functionality with option to preserve buffer list

- copilot-chat-common.el
- copilot-chat-markdown.el
- copilot-chat-org.el
- copilot-chat.el
- readme.org
> 84 copy kill ring

- copilot-chat-command.el
- copilot-chat-copilot.el
- copilot-chat-transient.el
feat: add multi-buffer management and switch to gfm-mode
- Add copilot-chat-add-buffers and copilot-chat-del-buffers for easier buffer handling
- Update copilot-chat-transient-buffers menu to handle multiple buffers
> feat: enhance buffer management in copilot-chat

- copilot-chat-command.el
- copilot-chat-common.el
- copilot-chat-copilot.el
- copilot-chat-curl.el
- copilot-chat-frontend.el
- copilot-chat-instance.el
- copilot-chat-markdown.el
- copilot-chat-org.el
- copilot-chat-prompt-mode.el
- copilot-chat-request.el
- copilot-chat-shell-maker.el
- copilot-chat.el
- readme.org
> 76 multiple instances

- .github/workflows/check.yml
Please merge after the warnings are gone, either here or in another PR.
> ci: fail on warnings

- copilot-chat-body.el
- copilot-chat-command.el
- copilot-chat-common.el
- copilot-chat-connection.el
- copilot-chat-copilot.el
- copilot-chat-curl.el
- copilot-chat-debug.el
- copilot-chat-frontend.el
- copilot-chat-git.el
- copilot-chat-instance.el
- copilot-chat-markdown.el
- copilot-chat-model.el
- copilot-chat-org.el
- copilot-chat-prompt-mode.el
- copilot-chat-request.el
- copilot-chat-shell-maker.el
- copilot-chat-spinner.el
- copilot-chat.el
Before tackling the following issue,
I reorganized the code.
Which had long been unorganized and hard to read.
In particular, spinner, model, body, git.
[git commit message don't work in submodule or worktree · Issue #133 · chep/copilot-chat.el](https://github.com/chep/copilot-chat.el/issues/133)
This PR implements a major refactoring of the copilot-chat package,
focusing on better module organization,
clearer separation of concerns,
and improved code structure.
- **Modular Architecture**: Split monolithic files into purpose-specific modules
- **Clearer Dependencies**: Reduced circular dependencies between modules
- **Code Organization**: Related functions grouped in logical modules
- `copilot-chat-body.el` - Request body creation
- `copilot-chat-connection.el` - Connection management
- …
> Comprehensive Module Restructuring for Improved Maintainability

- copilot-chat-command.el
- copilot-chat-shell-maker.el
> fix(buffers): remove references to killed buffers when refreshing chat list

- copilot-chat-request.el
> refactor(deps): add copilot-chat-connection requirement

- copilot-chat-git.el
Improve the function to get the top level directory of a git repository by handling special cases like git worktrees and submodules. Renamed function from `copilot-chat--git-root` to `copilot-chat--git-top-level` to better reflect its purpose.
Fix #133
> refactor(git): improve git repository root detection

- copilot-chat-curl.el
> chore: update copilot-chat-curl.el

- copilot-chat-org.el
> style(org): simplify chat tags and display format

- copilot-chat-command.el
Adding or removing buffers from buffer list was broken because of my previous PR.
> fix(buffer list): Fix `copilot-chat-list-add-or-remove-buffer`

- readme.org
> docs: Add badges to readme

- copilot-chat-frontend.el
- copilot-chat-markdown.el
- copilot-chat-org.el
- copilot-chat-shell-maker.el
- copilot-chat-spinner.el
> fix(frontend): improve spinner buffer handling

- copilot-chat-curl.el
I want to it for researching issues #182.
> feat(copilot-chat-debug): add debug logging for curl responses

- copilot-chat-curl.el
- copilot-chat-git.el
- copilot-chat-prompts.el
- readme.org
This PR introduces several improvements to the commit message generation workflow:
- **Persistent Commit Instance**  
Adds a persistent instance for Git commit message generation, improving context management and history handling across commit operations.
- **Difftastic Integration**  
Adds support for syntax-aware diffs using [difftastic](https://difftastic.wilfred.me.uk/) when available, resulting in more readable and informative diffs for commit messages.
- **Commit Message Regeneration (`copilot-chat-regenerate-commit-message`)**  
Introduces the `copilot-chat-regenerate-commit-message` function, allowing users to regenerate commit messages with optional additional instructions or a custom user prompt, reusing the previous context and history.
- **Improved Context and Error Handling** …
> feat(commit): enhance commit message generation with persistent context and difftastic support

- copilot-chat-command.el
- copilot-chat-copilot.el
- copilot-chat-curl.el
- copilot-chat-frontend.el
- copilot-chat-instance.el
- copilot-chat-markdown.el
- copilot-chat-org.el
- copilot-chat-shell-maker.el
- copilot-chat.el
- readme.org
Fixes #181
I managed to make it work for shell-maker but more tests are welcome !
> save and load
