chep/copilot-chat.el

Readme.md
After install `copilot-chat.el`, I ran `copilot-display`, but not found it.
Maybe, the correct function name is `copilot-chat-display`.
=> Fix a function name on README

copilot-chat-shell-maker.el
This tweaks `copilot-chat-shell-cb-prompt` to support streaming directly, rather than buffering internally to the (now removed) `copilot-chat-shell-maker-answer` variable.
In particular, the `shell-maker` `execute-command` is called with a lambda that accepts two arguments, `(lambda (response partial) ...)`. If `partial` is `t`, it seems to be treated as a streaming response and appended to the content, without starting a new prompt.
Reference: https://github.com/xenodium/chatgpt-shell/blob/f7b1f1e4b8a07c97deba92d9a23145d192ce715f/shell-maker.el#L632
Demo: 
https://github.com/user-attachments/assets/6fbe5657-d1f5-4ce9-933a-0cbd38d61dfb
Thanks for publishing this library, very nice!
=> Support streaming output in copilot-chat-shell-maker

copilot-chat-copilot.el
This upgrades from GPT-4 model to GPT-4o, mimicking https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/377
The new model appears to be noticeably quicker to provide responses, but hard to tell for sure!
Announcement: https://github.blog/changelog/2024-07-31-github-copilot-chat-and-pull-request-summaries-are-now-powered-by-gpt-4o/
=> Use gpt-4o model

copilot-chat-copilot.el, copilot-chat.el
Currently, running `copilot-chat-doc` or similar functions before `copilot-chat-display` results in a "No buffer named *Copilot-chat-prompt*" error. This commit extracts the buffer preparation segment from `copilot-chat-display` into a separate function, which is then invoked within `copilot-chat-ask-region`.
In addition, this commit fixes a typo in `copilot-chat-prompts`
=> Prepare Copilot Chat buffers in `copilot-chat-ask-region`

copilot-chat-copilot.el, copilot-chat-shell-maker.el, copilot-chat.el
I want to use customized prompt on `copilot-chat-review`, `copilit-chat-explain` commands.
So I tried to change to `defcustom` instead of `defconst`.
In `.emacs.d/init.el`:
```lisp
(setopt copilot-chat--prompt-review "MY OWN PROMPT")
```
=> Custom prompts for various commands, such as `copilot-chat-explain`, `-review` and others

Readme.md
Adding the link to the project. It is a complimentary for github copilot inside emacs.
=> Adding link to copilot.el project in README for code completion

copilot-chat-shell-maker.el, copilot-chat.el
This function will explain the symbol under point. It can be used to check the public functions / variables developer not familiar with, so that developer can stay inside emacs and get the info, and don't have to google the symbol and read the document.
Let me know if you have any thought. Thanks.
=> feat: Add `copilot-chat-explain-symbol-at-line` function

Readme.md, copilot-chat-shell-maker.el, copilot-chat.el
- `(copilot-chat-explain-defun)` ask copilot to explain current function under point.
- `(copilot-chat-custom-prompt-function)` ask copilot to apply a custom prompt to the function body under point. Eg. instruct on how to refactor the function.
- `(copilot-chat-review-whole-buffer)` ask copilot to review the current whole buffer. It can be used to review the full class, or, review the magit diff for my change, or other people's change.
- `(copilot-chat-switch-to-buffer)` switch to Copilot Chat buffer, side by side with the current code editing buffer.
=> feat: Add couple of shortcuts for content "under point"

copilot-chat-copilot.el
GitHub Copilot Chat comes with several pre-populated slash commands, and using the ones that are available will improve Copilot's efficiency and reliability.
=> fix: Prefer to use slash commands

Readme.md, copilot-chat-shell-maker.el, copilot-chat.el
This feature is about to make the copilot-chat discussion more smoothly. After developer asked question on the code, the *Copilot-chat* buffer will popup and show me the answer. It is possible that developer want to ask more question given the answer, to refine the answer / get the right code generated.
The solution in this code change is that, just press space key and enter following up question, copilot-chat will provide more response given the following up question. It make the discussion more smoothly with just a space key. (It can be changed to some other key)
=> Feat: Following up question in *Copilot-chat* buffer after asking question on the code

copilot-chat.el
The PR merged here has a wrong function name: https://github.com/chep/copilot-chat.el/pull/51
=> fix: fix function name

copilot-chat-common.el, copilot-chat.el, test_copilot-chat.el
The PR added two features about the discussion context:
1. Provide current programming language as context. It is based on the major mode of editing buffer. During using copilot-chat.el, I found that, during editing emacs lisp, if I ask copilot chat to write a hello world function, it still write the code in python. But if the current programming language was provided, it will write the hello world in emacs lisp. So it might be helpful. It is provided through copilot-chat--build-prompt-suffix function.
2. Optional suffix (copilot-chat-prompt-suffix). If it is configured as non-nil, it will be provided as part of context for every prompt sent to copilot-chat. It is useful if we want the reply from copilot-chat written in language other than English.
=> feat: add current programming language as context, and a configurable suffix

copilot-chat.el
What
===
Extensive additions to `copilot-chat-commit-prompt`
with detailed specifications and examples of Conventional Commits and type descriptions.
Why
===
I added a description of the actual commit type, since the recognition of the commit type was quite inaccurate.
Since token consumption does not have to be so truncated these days, I also added an actual example.
I tried it for a while with my personal settings, and I think the accuracy has improved there.
=> feat: add commit specification and example to prompt

copilot-chat.el
In order to support Emacs versions before v30, using the long form `autoload` comment as described here:
- https://magit.vc/manual/transient/FAQ.html#How-can-I-autoload-prefix-and-suffix-commands_003f-1
=> feat(transient): add autoload directives for transient commands

copilot-chat.el
This PR simply adds the interactive function `copilot-chat-hide` that hides both copilot chat and prompt; and registers it as a transient command.
=> Add transient command to hide copilot chat windows

copilot-chat-common.el
Unlike o1, it worked just by adding it.
=> feat: add `o3-mini` to `copilot-chat-model`

copilot-chat-common.el
It did not work with the family-specified `gemini-2.0-flash`.
Specific id must be specified.
=> feat: add Gemini 2.0 Flash model

copilot-chat-common.el
Claude 3.7 Sonnet had been recently rolled out in the copilot: https://github.blog/changelog/2025-02-24-claude-3-7-sonnet-is-now-available-in-github-copilot-in-public-preview/
=> feat: Add support for Claude 3.7 Sonnet model

copilot-chat-common.el, copilot-chat-curl.el, copilot-chat-request.el
This pull request includes several changes to support the new "o1" model in the `copilot-chat` module. The changes primarily involve adding specific handling for the "o1" model in various functions and ensuring compatibility with its unique response format.
I have confirmed that o1 responds.
However, I have not been able to check it under various conditions because of the rate limitation.
I confirmed that the fronend works with shell-maker and the backend works with curl.
=> fix: `o1` model to work closed #61

copilot-chat-common.el, copilot-chat-copilot.el, copilot-chat-curl.el, copilot-chat-markdown.el, copilot-chat-org.el, copilot-chat-request.el, copilot-chat-shell-maker.el, copilot-chat-transient.el, copilot-chat.el
Close #45
1. List models via the api `https://api.githubcopilot.com/models`;
2. Cache the models to ~/.cache/copilot-chat/models.json;
3. Improved set models:
4. Refine git commit get diff to ignore lock files;
5. Streaming messages;
=> feat(chat): implement models API

copilot-chat-common.el, copilot-chat.el
add `copilot-chat-model-ignore-picker` custom variable to filter model choices based on `model_picker_enabled` attribute.
Also add `copilot-chat--model-picker-enabled` function to apply filtering
with `copilot-chat--get-model-choices-with-wait` to prevent unnecessary models from being displayed.
=> feat: add `copilot-chat-model-ignore-picker` option

copilot-chat-markdown.el, copilot-chat-org.el, copilot-chat-shell-maker.el
The model name now appears in the buffer name,
but due to a refresh issue, it only shows the model when the buffer was created, causing me to be confused.
Also, when a model is changed after a response,
knowing which model the previous response was made with would reduce unnecessary queries.
Including the name of the model being used in the response header would solve these problems.
Either way, there is little overhead in displaying the information, since one line is used for the time display, etc.
=> feat: display the Copilot model name in response

copilot-chat-common.el
Since I am not fluent in English,
I wrote this document comment in Japanese and then translated it at DeepL.
This is why I did not notice the incorrect syntax in the code highlighting.
It is a minor detail, but due to my own mismanagement, I have corrected it.
=> docs: fix formatting of quoted words in docstring

copilot-chat.el
git diff needs to separate argument positions with `--` when specifying multiple files.
Before the fix, it worked when a single file was staged, but not when multiple files were specified.
=> fix: `copilot-chat--get-diff` work with multiple files

copilot-chat-curl.el
I am not sure why I made this mistake
when I should have made sure it could be done after I implemented it.
It is very likely that I did the wrong refactoring after the execution test.
=> fix: processing miss when waiting for the next data

copilot-chat.el, readme.org
Allow users to provide a custom prompt directly to the function copilot-chat-custom-prompt-selection. If no custom prompt is provided, the function will read from the mini-buffer.
This makes it easy to for users to create customized functions for example:
```elisp
(defun copilot-chat-correct-typos ()
(interactive)
(copilot-chat-custom-prompt-selection
"Please fix typos in the following text "))
```
Another enhancement is: if the region is inactive, use the whole buffer.
=> `copilot-chat-custom-prompt-selection` add optional argument "prompt"

copilot-chat-curl.el
What
===
Stop spinner when o1(non-stream) response is received.
Why
===
Because the process to stop the spinner did not exist in the receiver of the response on the o1 side,
the spinner did not stop.
=> fix: stop spinner on o1 response

copilot-chat-curl.el
The previous operation would have been done in the current buffer,
so if I focused on a different buffer and waited for Copilot Chat to respond,
the `Thinking` string would cover up a lot of the buffer.
Even though it disappears after the last focus,
it is hard to read and uncomfortable to work with the output on the side.
=> fix: move remove operation of old spiner overlay to chat buffer

.github/workflows/check.yml
Because resolved [Please release for version · Issue #31 · leotaku/elisp-check](https://github.com/leotaku/elisp-check/issues/31).
=> ci: pin elisp-check action version to v1.4.1

copilot-chat-command.el, copilot-chat-frontend.el, copilot-chat-instance.el, copilot-chat-shell-maker.el, copilot-chat.el
feat!: remove magit usage and add region-based approach for code chat commands
- Replaced magit-based diff logic with asynchronous git commands using aio.
- Changed code chat commands (explain, review, doc, fix, optimize, test) to accept region arguments.
- Removed magit and related dependencies.
BREAKING CHANGE: function signatures now require beg and end parameters.
fix: require frontend dependencies on demand
Fix #124
=> Remove hard dependencies on magit and require frontend dependencies on demand

copilot-chat-command.el
- **fix: use `--absolute-git-dir` instead of `--show-toplevel`**
- **fix: avoid pager when running git diff commands**
- **fix: delay commit message insertion for `git-commit-setup-hook` compatibility**
The previous behavior of committing normally using magit was broken without notice, so this is an emergency fix.
I know that using timer is a dirty way to do it, but there was no other way.
The following PRs have been fixed.
[Remove hard dependencies on magit and require frontend dependencies on demand by kiennq · Pull Request #128 · chep/copilot-chat.el](https://github.com/chep/copilot-chat.el/pull/128)
=> fix: insert commit message to compatible existing environments

copilot-chat-shell-maker.el
Maybe `shell-maker-start` make directory by name.
So I'm `~/.emacs.d` have two directory `copilot-chat` and `copilot-chat `.
```
❯ ll
合計 35M
drwxr-xr-x  20 ncaq ncaq 4.0K  3月 30 15:28  ./
drwxr-xr-x  54 ncaq ncaq 4.0K  3月 30 15:34  ../
drwxr-xr-x   5 ncaq ncaq 4.0K  2月 21 15:25  .cache/
drwxr-xr-x  11 ncaq ncaq 4.0K  3月 30 15:28  .git/
drwxr-xr-x   2 ncaq ncaq 4.0K  3月 30 15:34  auto-save-file/
drwx------   2 ncaq ncaq 4.0K  3月 30 15:31  auto-save-list/
drwxr-xr-x   3 ncaq ncaq 4.0K  3月 30 15:32  copilot-chat/
drwxr-xr-x   3 ncaq ncaq 4.0K  3月 30 15:28 'copilot-chat '/
drwxr-xr-x   3 ncaq ncaq 4.0K 12月  6 17:32  eclipse.jdt.ls/
drwxr-xr-x   3 ncaq ncaq 4.0K  3月 21 15:19  eln-cache/
drwxr-xr-x 182 ncaq ncaq  12K  3月 28 17:58  elpa/
drwxr-xr-x   3 ncaq ncaq 4.0K  7月 31  2023  elpy/ …
```
=> fix(shell-maker): copilot chat use directory to one

copilot-chat-command.el
This change ensures that the chat buffer is recentered to improve visibility and usability when interacting with the Copilot chat instance.
=> fix(chat): ensure chat buffer is recentered after writing

copilot-chat-org.el
Refactored `copilot-chat--org-create-req` to handle the `no-context` parameter. If `no-context` is true, the function now directly returns the prompt without additional formatting instructions. This improves flexibility for specific use cases like generating commit messages.
Relation : #145
=> feat(org): enhance request creation with no-context handling

copilot-chat-body.el, copilot-chat-command.el, copilot-chat-curl.el, copilot-chat-markdown.el, copilot-chat-org.el, copilot-chat-prompt-mode.el, copilot-chat-shell-maker.el, readme.org
`copilot-chat-display` is the most common starting command, is it not?
Can it take the alias `copilot-chat`?
I think this will help new users who intuitively look for a starting command, usually the name of the package.
------------
I have tested this by evaluating
```
(defalias 'copilot-chat 'copilot-chat-display)
```
The result is a new command:
```M-x copilot-chat```
=> alias `copilot-chat` command to `copilot-chat-display`

copilot-chat-prompts.el
Unlike before, now that instance separation has been reorganized,
the only place where `copilot-chat-prompt` is used is in `copilot-chat--create-req`.
That means initialization there is no longer strictly necessary,
so to avoid any mix‑ups, we’ll set the default value to an empty string.
Ideally, I’d like to split this field by natural language or frontend type,
but for now we’ll just solve the immediate problem.
=> fix: initialization of `copilot-chat-prompt` to empty closed #145

copilot-chat-body.el, copilot-chat-git.el, copilot-chat-instance.el, readme.org
* Add config `copilot-chat-use-git-commit-instruction-files`
* Breaking Change from `copilot-chat-use-instruction-files` to `copilot-chat-use-copilot-instruction-files`
* To be generic for read file operation
* Read `.github/git-commit-instructions.md` file when commit
* Add `copilot-chat-type` for detecting git commit
=> feat!: Add support `.github/git-commit-instructions.md` closed #160

copilot-chat-command.el, readme.org
- Add new customization variables to control path display:
- Add copilot-chat-list-show-path to toggle full path display
- Add copilot-chat-list-show-relative-path for relative/absolute path
- Update buffer list to respect these settings
- Add header line showing current directory
- Update documentation with new options
Fixes #154
=> feat(ui): enhance buffer list display with path options

.github/workflows/check.yml
Do not run on double action on PR.
=> ci: restrict workflow to run only on master branch for push events

.dir-locals.el, .github/workflows/check.yml, copilot-chat-body.el, copilot-chat-command.el, copilot-chat-common.el, copilot-chat-connection.el, copilot-chat-copilot.el, copilot-chat-curl.el, copilot-chat-debug.el, copilot-chat-frontend.el, copilot-chat-git.el, copilot-chat-instance.el, copilot-chat-markdown.el, copilot-chat-model.el, copilot-chat-org.el, copilot-chat-prompt-mode.el, copilot-chat-prompts.el, copilot-chat-request.el, copilot-chat-shell-maker.el, copilot-chat-spinner.el, copilot-chat-transient.el, copilot-chat.el
I have introduced a powerful code formatter, [elisp-autofmt](https://codeberg.org/ideasman42/emacs-elisp-autofmt/).
This code formatter has an opinionated approach comparable to prettier.
For collaborative work with multiple people,
I determined that such a prescriptive approach would prevent conflicts over trivial style differences.
I personally feel some resistance to this strict automatic formatting approach.
However, from my experience with prettier and fourmolu,
I've learned that you eventually adapt,
and it becomes easier as you no longer need to worry about minor code style details.
=> style: apply elisp-autofmt

copilot-chat-body.el, copilot-chat-command.el, copilot-chat-common.el, copilot-chat-connection.el, copilot-chat-copilot.el, copilot-chat-curl.el, copilot-chat-debug.el, copilot-chat-frontend.el, copilot-chat-git.el, copilot-chat-instance.el, copilot-chat-markdown.el, copilot-chat-model.el, copilot-chat-org.el, copilot-chat-prompt-mode.el, copilot-chat-prompts.el, copilot-chat-request.el, copilot-chat-shell-maker.el, copilot-chat-spinner.el, copilot-chat-transient.el, copilot-chat.el
elisp-autofmt uses this variable to truncate lines but the python command does not read `.dir-locals.el` so we have to add this variable at the end of all files.
=> refactor: add fill-column variables in files

copilot-chat-body.el, copilot-chat-curl.el, copilot-chat-instance.el, copilot-chat-request.el, copilot-chat.el, readme.org
Introduce functionality to send images to Copilot when using the gpt-4o model. Added a new function `copilot-chat--image-to-base64` to convert image files to base64 strings and updated the request creation logic to include image data when applicable.
BREAKING CHANGE: Requires gpt-4o model for image handling.
Fixes #121
=> feat(chat): add support for image handling with gpt-4o model

copilot-chat-body.el, copilot-chat-command.el, copilot-chat-curl.el, copilot-chat-instance.el, copilot-chat-model.el, copilot-chat-request.el
This change improves how we detect model capabilities:
- Replace hardcoded model name checks (model-is-gpt-4o, model-is-o1)
- Add functions to check for vision and streaming support from model capabilities
- Fix streaming vs non-streaming payload structure which was inverted
- Enable vision support for all models that support it, not just gpt-4o
This makes the code more future-proof for new models and
ensures we properly handle models with different capability combinations.
=> feat: dynamic model capability detection

copilot-chat-markdown.el
`copilot-chat--markdown-get-spinner-buffers` was returning a buffer instead of a list if `copilot-chat-follow` was `t`.
fixes #193
=> 193 spinner fail

copilot-chat-backend.el, copilot-chat-command.el, copilot-chat-copilot.el, copilot-chat-curl.el, copilot-chat-request.el
- Introduced `cancel-fn` in backend definitions to support request cancellation.
- Added `copilot-chat-cancel` command for user-initiated cancellations.
- Implemented backend-specific cancellation logic for curl and request backends.
- Enhanced instance management to handle process termination and cleanup.
fixes #198
=> feat(chat): add cancel functionality for Copilot Chat requests
